using System.Reflection;

namespace PotatoMaker.GUI.Services;

/// <summary>
/// Exposes the app's semantic version and full informational version.
/// </summary>
public interface IAppVersionService
{
    string SemanticVersion { get; }

    string InformationalVersion { get; }

    string DisplayVersion { get; }
}

/// <summary>
/// Reads version metadata from the built assembly attributes generated by the .NET SDK.
/// </summary>
public sealed class AssemblyAppVersionService : IAppVersionService
{
    public AssemblyAppVersionService()
        : this(typeof(AssemblyAppVersionService).Assembly)
    {
    }

    public AssemblyAppVersionService(Assembly assembly)
        : this(
            assembly.GetCustomAttribute<AssemblyInformationalVersionAttribute>()?.InformationalVersion,
            assembly.GetName().Version)
    {
        ArgumentNullException.ThrowIfNull(assembly);
    }

    public AssemblyAppVersionService(string? informationalVersion, Version? assemblyVersion = null)
    {
        string fallbackVersion = assemblyVersion?.ToString(3) ?? "0.0.0";
        InformationalVersion = string.IsNullOrWhiteSpace(informationalVersion)
            ? fallbackVersion
            : informationalVersion.Trim();
        SemanticVersion = StripBuildMetadata(InformationalVersion, fallbackVersion);
        DisplayVersion = $"v{SemanticVersion}";
    }

    public string SemanticVersion { get; }

    public string InformationalVersion { get; }

    public string DisplayVersion { get; }

    private static string StripBuildMetadata(string informationalVersion, string fallbackVersion)
    {
        string semanticVersion = informationalVersion.Split('+', 2, StringSplitOptions.TrimEntries)[0];
        return string.IsNullOrWhiteSpace(semanticVersion)
            ? fallbackVersion
            : semanticVersion;
    }
}
